name: Loyverse to Notion Sync

on:
  schedule:
    # Run every hour at minute 0
    - cron: '0 * * * *'
  workflow_dispatch:  # Allows manual triggering from GitHub UI

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y jq curl
      
      - name: Restore cache
        id: cache-restore
        uses: actions/cache/restore@v3
        with:
          path: |
            .loyverse_cache.json
            .last_receipt.txt
          key: loyverse-cache-${{ github.sha }}
          restore-keys: |
            loyverse-cache-
      
      - name: Run sync script
        env:
          LOYVERSE_API_KEY: ${{ secrets.LOYVERSE_API_KEY }}
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          NOTION_DB_ID: ${{ secrets.NOTION_DB_ID }}
        run: |
          chmod +x sync.sh
          ./sync.sh
      
      - name: Save cache
        if: always()
        uses: actions/cache/save@v3
        with:
          path: |
            .loyverse_cache.json
            .last_receipt.txt
          key: loyverse-cache-${{ github.sha }}
