name: Loyverse to Notion Sync

on:
  schedule:
    # Runs every hour from 7am-12am BNT (23:00 UTC - 15:00 UTC)
    - cron: '0 23,0-15 * * *'
  workflow_dispatch:
    inputs:
      start_receipt:
        description: 'Starting receipt number (leave empty to continue from last)'
        required: false
        type: string

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y jq curl
      
      - name: Download cache from Gist
        continue-on-error: true
        run: |
          curl -f -H "Authorization: token ${{ secrets.GIST_TOKEN }}" \
            https://api.github.com/gists/${{ secrets.GIST_ID }} | \
            jq -r '.files."loyverse_cache.json".content // "{}"' > .loyverse_cache.json
          
          curl -f -H "Authorization: token ${{ secrets.GIST_TOKEN }}" \
            https://api.github.com/gists/${{ secrets.GIST_ID }} | \
            jq -r '.files."last_receipt.txt".content // "Value"' > .last_receipt.txt
      
      - name: Set starting receipt if provided
        if: github.event.inputs.start_receipt != ''
        run: |
          echo "${{ github.event.inputs.start_receipt }}" > .last_receipt.txt
          echo "Starting from receipt: ${{ github.event.inputs.start_receipt }}"
      
      - name: Run sync script
        env:
          LOYVERSE_API_KEY: ${{ secrets.LOYVERSE_API_KEY }}
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          NOTION_DB_ID: ${{ secrets.NOTION_DB_ID }}
        run: |
          chmod +x sync.sh
          ./sync.sh
      
      - name: Upload cache to Gist
        if: always()
        run: |
          CACHE_CONTENT=$(cat .loyverse_cache.json | jq -Rs .)
          RECEIPT_CONTENT=$(cat .last_receipt.txt | jq -Rs .)
          
          curl -X PATCH \
            -H "Authorization: token ${{ secrets.GIST_TOKEN }}" \
            -H "Content-Type: application/json" \
            https://api.github.com/gists/${{ secrets.GIST_ID }} \
            -d "{\"files\":{\"loyverse_cache.json\":{\"content\":$CACHE_CONTENT},\"last_receipt.txt\":{\"content\":$RECEIPT_CONTENT}}}"
