name: Loyverse to Notion Sync

on:
  schedule:
    # Runs at minutes 0 of hours 23,0-15 UTC (7am-12am BNT/UTC+8)
    # BNT 7am = UTC 11pm (23:00) previous day
    # BNT 12am = UTC 4pm (16:00) same day
    - cron: '0 23 * * *'    # BNT 7am
    - cron: '0 0-15 * * *'  # BNT 8am-12am
  workflow_dispatch:
    inputs:
      start_receipt:
        description: 'Starting receipt number (leave empty to continue from last)'
        required: false
        type: string

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y jq curl
      
      - name: Set starting receipt if provided
        if: github.event.inputs.start_receipt != ''
        run: |
          echo "${{ github.event.inputs.start_receipt }}" > .last_receipt.txt
          echo "Starting from receipt: ${{ github.event.inputs.start_receipt }}"
      
      - name: Run sync script
        env:
          LOYVERSE_API_KEY: ${{ secrets.LOYVERSE_API_KEY }}
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          NOTION_DB_ID: ${{ secrets.NOTION_DB_ID }}
        run: |
          chmod +x sync.sh
          ./sync.sh
      
      - name: Commit and push cache files
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .loyverse_cache.json .last_receipt.txt 2>/dev/null || true
          if ! git diff --quiet --cached; then
            git commit -m "Update sync cache [skip ci]"
            git push
          else
            echo "No changes to commit"
          fi
